services:
  front:
    build:
      context: ./test-fe
      dockerfile: dockerfile
    ports:
      - "81:80"
    volumes:
      - ./test-fe/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    depends_on:
      - back

  back:
    build:
      context: ./test-be
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - mynetwork
    depends_on:
      db:
         condition: service_healthy
  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3303:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      retries: 3
      start_period: 5s

networks:
  mynetwork:
    driver: bridge
