
FROM maven:latest AS build
WORKDIR /build
# Copy the pom.xml file first for better caching
COPY pom.xml .
# Download all dependencies
RUN mvn dependency:go-offline -B
# Copy source files
COPY src ./src
# Build the application
RUN mvn package -DskipTests

FROM openjdk:21 
WORKDIR /app 
COPY target/test-be-0.0.1-SNAPSHOT.jar /app/app.jar 
EXPOSE 8080 
CMD ["java", "-jar", "app.jar"] 

